# https://github.com/cachix/devenv/blob/bc8b21628907c726c74094cedc439c10a455cdb7/docs/src/integrations/github-actions.md?plain=1#L128-L160
name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile add nixpkgs/871b9fd269ff6246794583ce4ee1031e1da71895#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
      - name: Run a single command in the devenv shell
        run: devenv shell hello
      - name: Run a multi-line command in the devenv shell
        shell: devenv shell bash -- -e {0}
        run: |
          hello
      - run: devenv shell release
      - run: tar czf word.tar.gz rplugin/node
      # https://github.com/softprops/action-gh-release/blob/403a5240f3837fa857f642062e05aad6bb3391ca/README.md?plain=1#L110-L114
      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        if: github.ref_type == 'tag'
        with:
          files: Release.txt
# https://github.com/softprops/action-gh-release/blob/403a5240f3837fa857f642062e05aad6bb3391ca/README.md?plain=1#L289-L290
permissions:
  contents: write
